language: php

dist: xenial

services:
  - mysql

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: true

before_script:
  - composer update
  - mysql -e "CREATE USER 'event_sourcing'@'localhost' IDENTIFIED BY 'event_sourcing123';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON json_event_store.* TO 'event_sourcing'@'localhost';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON json_snapshot_store.* TO 'event_sourcing'@'localhost';" -uroot
