name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '7.1', '7.2', '7.3', '7.4' ]

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Docker
        run: docker-compose up -d

      - name: composer
        run: composer install

      - name: Create table
        run: |
          mysql -e "CREATE DATABASE IF NOT EXISTS `json_snapshot_store`;" -uroot
          mysql -e "GRANT ALL PRIVILEGES ON json_snapshot_store.* TO 'event_sourcing'@'localhost';" -uroot


      - name: tests
        run: ./vendor/bin/phpunit