name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '7.1', '7.2', '7.3', '7.4' ]

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Setup MySQL database
        run: docker-compose up -d

      - name: Wait until MySQL ready
        run: |
          while ! docker exec event-sourcing_mysql_1 mysqladmin --password=event_sourcing ping &> /dev/null ; do
              echo "Waiting for database connection..."
              sleep 2
          done

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: ./vendor/bin/phpunit