name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '7.1', '7.2', '7.3', '7.4' ]

    steps:
      - uses: actions/checkout@v2

      - name: Install MySQL
        run: |
          - sudo apt-get update && sudo apt-get install mysql-server
          - mysql -e "CREATE USER 'event_sourcing'@'localhost' IDENTIFIED BY 'event_sourcing123';" -uroot
          - mysql -e "GRANT ALL PRIVILEGES ON json_event_store.* TO 'event_sourcing'@'localhost';" -uroot
          - mysql -e "GRANT ALL PRIVILEGES ON json_snapshot_store.* TO 'event_sourcing'@'localhost';" -uroot

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: composer
        run: composer install

      - name: tests
        run: ./vendor/bin/phpunit