name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install PHP7
        run: apt-get purge php-* && apt-get install php-7.4

      - name: composer
        run: composer install